AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

DotPosition:
  EnforcedStyle: trailing

ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - '**/*.rake'
    - 'app/admin/**/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['^ *#']
  Exclude:
    - '**/*.json.jbuilder'

MethodLength:
  Max: 10

Rails/SkipsModelValidations:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
