require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
  NewCops: enable
  SuggestExtensions: false

Rails:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 80
  AllowedPatterns: ['^ *#']
  Exclude:
    - '**/*.json.jbuilder'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - '**/*.rake'
    - 'app/admin/**/*.rb'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 10

Rails/SkipsModelValidations:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false
